### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by muppeth** [alexr4535/siglo#1]
Does siglo send notifications to the watch?

**Comment by alexr4535** [comment]
All Siglo does is update the time and disconnect, and soon it will be able to OTA update and disconnect. I don't know if I want to make it do things like stay synced to the phone at this point in time.

**Comment by sirnewton01** [comment]
I wondered about this myself. Maybe gnome/kde could plug in bluetooth gatt notifications into their notification systems directly.

**Comment by alexr4535** [comment]
I was thinking some kind of daemon code that keeps running in the background. when it picks something up on the dbus (gnome or kde notification) it simply takes the text and pushes it to the connected pinetime.

**Comment by sirnewton01** [comment]
Having done something with free desktop notifications recently (long story: my kids needed a thing that would indicate their difference recess times) one problem that you might face is that those notifications are removed from dbus by the desktop environment's notifier. So, by the time my program tried to get the notifications they were gone. Maybe I did something wrong or could have done something different, but I think that in this case there can only be one consumer (many producers) of the desktop notifications.

**Comment by sirnewton01** [comment]
I can't wait to give this a try. Thank you!

**Comment by sirnewton01** [comment]
This is working great so far.

**Comment by alexr4535** [comment]
good to hear, how does it hold up after suspend/resume cycle?

    On Saturday, May 1, 2021, 5:44:40 PM CDT, Chris McGee ***@***.***> wrote:  
 
 


This is working great so far.
