### ISSUE TITLE
Ability to choose device

### ISSUE THREAD

**Issue by pfeerick** [alexr4535/siglo#14]
Currently appears to assume that you have 1 and only 1 Pinetime/Infinitime device.

**Comment by alexr4535** [comment]
I have mixed feelings about this feature. I know some have more than one pinetime, but the watches stop their BLE servers so quickly that its not often you have more than one watch scanned at a time.

**Comment by JF002** [comment]
I actually have 2 devkits, 1 sealed unit and 1 dev board running InfiniTime on my desk right now, but I guess most of the time, there will be only 1 PineTime in BLE range.

Using a command line parameter to specify the BLE MAC address to look for could be a good compromise ?

**Comment by pfeerick** [comment]
I have two Dev units, and one of three sealed units in range right now, as
the stack not only when paired, but also for as long as the screen is on.

So what happens when both the watch you're wearing and the Dev unit on the
table are active, and you can only sync one? I can understand coding it
with one watch visible in mind, but multiwatch combinations are going to
become more frequent, and I think should either be catered for via the GUI
since this is a GUI app, or a note to ensure the pinetime/device running
InfiniTime needs to have the screen active for it to be detected. ;)

Just my 2 cents on this, as a UX discussion point.

**Comment by alexr4535** [comment]
By default, siglo should be fast and efficient for users with one watch advertising, because this is the majority of users.
I propose:
- Continue selecting the first watch available, by default
- Add a menu option which, when toggled, will collect and show a list of mac-addresses the user can select on app start-up

**Comment by pfeerick** [comment]
Sorry, meant to reply to this and got distracted. I'll try the new version out later today hopefully, but what you proposed was all I thought was needed... just some way of saying "Hey, no, not that one, this one!" behind a button or menu option. ;)
