### ISSUE TITLE
Error running meson on Mobian/Debian

### ISSUE THREAD

**Issue by sirnewton01** [alexr4535/siglo#2]
Hi,

I'm trying to build the tools, but I'm getting an error running meson and I can't seem to figure out what's wrong from the logs. Here's what I have so far:

```
$ meson build
The Meson build system
Version: 0.56.2
Source dir: /home/cmcgee/git/siglo
Build dir: /home/cmcgee/git/siglo/build
Build type: native build
Project name: siglo
Project version: 0.1.0
Host machine cpu family: aarch64
Host machine cpu: aarch64
WARNING: Gettext not found, all translation targets will be ignored.

data/meson.build:1:0: ERROR: Tried to assign an invalid value to variable.

A full log can be found at /home/cmcgee/git/siglo/build/meson-logs/meson-log.txt
```

The full log just repeats the same as above.

**Comment by alexr4535** [comment]
on debian, make sure `build-essential` meta package is installed. I think it contains gettext and other necessary packages.

**Comment by sirnewton01** [comment]
Thanks, it was gettext that was missing. It wasn't part of build-essential, but I was able to install it using "apt install getttext" I've gotten past this error. Thanks!
