### ISSUE TITLE
Add message to log while downloading

### ISSUE THREAD

**Issue by pfeerick** [alexr4535/siglo#23]
I was wondering if this is the right place to fire a log message indicating the file is being downloaded - just before this line. i.e. so there is a some response from the GUI after the flash button is pressed before switching to the actual OTA flash screen and progress. 

https://github.com/alexr4535/siglo/blob/1a297a367741894a30c9cc386b490e287f9b6c65/src/window.py#L226

**Comment by alexr4535** [comment]
It's been a while but i am not ignoring this. This should be fairly simple to implement and I will look into it soon.

**Comment by pfeerick** [comment]
No problem... life gets in the way ;)
