### ISSUE TITLE
block suspend from happening during firmware update

### ISSUE THREAD

**Issue by alexr4535** [alexr4535/siglo#31]
see title

**Comment by pfeerick** [comment]
This looks like it could be promising... needs super cow (sudo) to work apparently though... https://github.com/np-8/wakepy

**Comment by alexr4535** [comment]
sudo is a no-no... gsettings could the the way to go. i would not know how to make this work for plasma mobile though

**Comment by pfeerick** [comment]
Yeah, I don't like it either. I think after reading something about python
GATT I'll give in on that point though... Namely doing `.discover()` is
pointless as it requires sudo to work... no wonder I have sometimes have to
do a manual scan  before siglo picks up device... :(

> Note that it must be run as root because on Linux, Bluetooth discovery by
default is a restricted operation.
