### ISSUE TITLE
Improvements for your notifications - Info only :)

### ISSUE THREAD

**Issue by pfeerick** [alexr4535/siglo#32]
I've been playing around with notifications more, and have managed to get the title and message to show up properly...

```
alert_category = '0' # simple alert
alert_number = '0' # 0-255
title = 'Alert'
msg = str.encode(alert_category) + str.encode(alert_number) + str.encode('\0') + str.encode(title) + str.encode('\0') + str.encode(args.notify)

new_alert_characteristic.write_value(msg)
```

If I'm reading 3.5 of this correctly (https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=429632)  alert_category 5 should be SMS, and 3 for phone... but either my pythonese really is crap and I'm formatting it wrong, or something else is amiss...  3.119 has the alert characteristic juicy goodness. The '\0' separator stuff is InfiniTime specific to allow title / message splitting...

**Comment by alexr4535** [comment]
thanks, now the "Title" is the Chatty sender
