### ISSUE TITLE
btmgmt portability across distributions

### ISSUE THREAD

**Issue by Avamander** [alexr4535/siglo#4]
In this file https://github.com/alexr4535/siglo/blob/main/src/bluetooth.py#L30, the `btmgmt` binary is invoked from PATH. But it is not installed/available on all distros. A more universal alternative would potentially be to use the Python package with the same name ([btmgmt](https://pypi.org/project/btmgmt/)), it just requires a compiler and the headers, the command syntax is identical in the current use-case and probably many others.

It's possible to write a wrapper that behaves mostly the same:
```
#!/usr/bin/python3
import btmgmt
import sys
btmgmt.command(*sys.argv[1:])
```

It'd also be possible execute that wrapper if `btmgmt` itself doesn't exist

**Comment by alexr4535** [comment]
I wanted to use btmgmt python module but was unsure how to capture stdout as a variable as it only seemed to return int values (basically error codes)

**Comment by Avamander** [comment]
It would be possible to use the same subprocess method but execute that wrapper, it is a bit indirect but it'd also protect against btmgmt misbehaving.

**Comment by alexr4535** [comment]
I have reached out to the author of the `btmgmt` module

**Comment by alexr4535** [comment]
they added the function, but i'm not sure how to call it in a way that doesn't interrupt the application UI. Any ideas @Avamander ?

**Comment by alexr4535** [comment]
So it turns out the new function works when run from terminal but mysteriously doesn't when run via and application launcher. I've created a bug with the module author:  https://github.com/BOJIT/btmgmt/issues/5
