### ISSUE TITLE
Alignment issue (cosmetic, minor)

### ISSUE THREAD

**Issue by pfeerick** [alexr4535/siglo#40]
Every now and then, everything seems to shunt to the right, and might then later refresh and go back where it belongs. An example of where it would occurs is after flashing one firmware, and then proceeding to flash a second. The progress bar, text, drop downs etc are pushed a little to the right. Whilst it was flashing everything suddenly jumped back to where it should be. 

A cosmetic issue only.

0.7.1

**Comment by alexr4535** [comment]
Please install 0.8 and see if your problem persists

**Comment by pfeerick** [comment]
Not as far as I can tell. one or two minor regressions have been added... 
* no feedback during download, 
* back button can be clicked whilst downloading or updating, meaning you lose track of update progress or crash the update
* either progress bar and text is slightly too low, or cancel button is too high as it gets overlapped by the status text during the update. 

All in all, 0.8 is still a great interface improvement! :)
