### ISSUE TITLE
Cannot update firmware from file

### ISSUE THREAD

**Issue by JF002** [alexr4535/siglo#50]
I've just built version 0.8.0. Very nice UI improvements, btw! :1st_place_medal: 

I tried flash a development build of InfiniTime using Siglo, but the button "Update firmware" is disabled, even after selecting a DFU ZIP file.

![image](https://user-images.githubusercontent.com/2261652/119035307-b874a680-b9af-11eb-8673-21ab392a4c16.png)

**Comment by TheBird956** [comment]
I am having the same problem. I'm running Siglo on Ubuntu 20.10

**Comment by alexr4535** [comment]
thanks! lots of changes in 0.8 means lots of things breaking!
this functionality should be fixed as of v0.8.1

**Comment by JF002** [comment]
Yep thanks! I've just tested v0.8.2 and it works perfectly!
Great job!
