### ISSUE TITLE
Sms notifications broke, what version works?

### ISSUE THREAD

**Issue by plaurent** [alexr4535/siglo#53]
In a previous version experimental pairing allowed sms notifications from chatty under Mobian to work. What version was that?  And will Sms notifications be coming back soon?

**Comment by alexr4535** [comment]
this broke with the new UI refresh for v0.8.0, so if you want SMS notifications you need to checkout the tag before that for now. (v0.7.4) Closing this as its a duplicate of https://github.com/alexr4535/siglo/issues/49

**Comment by plaurent** [comment]
Thank you!
