### ISSUE TITLE
Provide on Flathub

### ISSUE THREAD

**Issue by jwillikers** [alexr4535/siglo#57]
I'd love to be able to get this directly from Flathub.

**Comment by arteeh** [comment]
I've uploaded an application to Flathub before, I can help if there's any confusion or difficulty getting Siglo on Flathub.

Here's the wiki where the process of submitting is explained: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by alexr4535** [comment]
PR Created. I will keep this ticket open until the submission is accepted.

https://github.com/flathub/flathub/pull/2421

**Comment by jwillikers** [comment]
@alexr4535 Thanks for all the work on this!

**Comment by alexr4535** [comment]
Ok, now i have to figure out how to build the python submodules

**Comment by jwillikers** [comment]
You should be able to do this with the following commands.

```
python3 -m pip install requirements-parser
git clone https://github.com/flatpak/flatpak-builder-tools.git
python3 flatpak-builder-tools/pip/flatpak-pip-generator --runtime org.gnome.Sdk//40 gatt dbus-python requests pyxdg
```

This will produce a `python3-modules.json` file which you can include directly in the Flatpak manifest like so.

```json
    "modules" : [
        "python3-requests.json",
        {
            "name" : "siglo",
            "builddir" : true,
            "buildsystem" : "meson",
            "sources" : [
                {
                    "type" : "git",
                    "url" : "https://github.com/alexr4535/siglo",
                    "tag" : "v0.8.6"
                }
            ]
        }
    ]
```

If all goes well, there won't be any hidden build dependencies you also have to install for the Python dependencies and everything will just build.
If the build fails, feel free to let me know if you need help.

**Comment by jwillikers** [comment]
Darn, I made a typo. You should include `python3-modules.json` not `python3-requests.json` as shown here.

```json
 "modules" : [
        "python3-modules.json",
```

**Comment by jwillikers** [comment]
Also, you might consider making the local Flatpak manifest track the latest Git commit on the `master` branch, and use an app-id with the `.Devel` suffix to differentiate from a release version installed from Flathub.

An example of using the latest Git commit:

```json
{
            "name" : "siglo",
            "builddir" : true,
            "buildsystem" : "meson",
            "sources" : [
                {
                    "type" : "git",
                    "path" : "."
                }
            ]
        }
```

The development app-id would change from `com.github.alexr4535.siglo.json` to com.github.alexr4535.siglo.Devel.json` in this repository. The app-id in your Flathub Flatpak manifest should remain as it is.

**Comment by jwillikers** [comment]
Merged! It should show up on Flathub within about a day. Thanks again for the app and all your work!

**Comment by alexr4535** [comment]
great, once it shows up, should we include something in the readme?

**Comment by jwillikers** [comment]
Good idea! The README should probably point users at the Flatpak on Flathub for those that just want to run the app. If you want, you can provide the commands to add the Flathub repo and run `flatpak install flathub com.github.alexr4535.siglo` from the command-line. It's up, by the way! The link is here: https://flathub.org/apps/details/com.github.alexr4535.siglo
