### ISSUE TITLE
Gtk Version Requirement

### ISSUE THREAD

**Issue by ccoupe** [alexr4535/siglo#62]
I use an older Linux, Mint 19.3 and Siglo fails with  ` AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'`. Evidently this is because Gtk 3.30 is the first version to support Template and I was on 3.26.  You might want to note that in the requirements section of the Readme.  

I do have another box with a later Gtk so I was able to get PineTime updated so I'm good.

**Comment by alexr4535** [comment]
thanks, i will be sure to add a Requirements section and include Gtk >= 3.30
