### ISSUE TITLE
App get stuck on startscreen at pinephone

### ISSUE THREAD

**Issue by ediying** [alexr4535/siglo#63]
installed Os on pinephone: Manjaro-ARM-plasma-mobile-pinephone-20210803

**Comment by alexr4535** [comment]
I am not able to reproduce. I installed a nightly build of Manjaro ARM Plasma for PinePhone today, installed the flatpak from flathub, and everything works when I make sure bluetooth is enabled: 
![image](https://user-images.githubusercontent.com/25991564/130153246-47e1c9cb-e447-4ba9-85b9-ffc3c9ec299e.png)
