### ISSUE TITLE
Is this app proprietary?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [alexr4535/siglo#65]
Looking at the license file of this repo, it says MPLv2, however, in Flathub, I see it says proprietary:

![image](https://user-images.githubusercontent.com/50847364/128618673-a128b70e-b41c-42d9-8698-5cb3b537a551.png)

https://flathub.org/apps/details/com.github.alexr4535.siglo

**Comment by alexr4535** [comment]
no, its not proprietary. any idea how to fix this, @jwillikers ?

**Comment by TheEvilSkeleton** [comment]
Okay, I'll submit an MR then.

**Comment by jwillikers** [comment]
Everything displayed in app stores / the Flathub website comes from the AppStream metadata file, i.e. `com.github.alexr4535.siglo.appdata.xml`. The `project_license` XML attribute is the one that needs fixed, which @TheEvilSkeleton  has corrected in PR #68.
