### ISSUE TITLE
DFU stalls on infinitime -> wasp-os reloader

### ISSUE THREAD

**Issue by OrgansWithoutBodies** [alexr4535/siglo#74]
The [pinetime wiki article on switching between infinitime & wasp-os](https://wiki.pine64.org/wiki/Switching_your_PineTime_between_InfiniTime_and_Wasp-os) says to install reloader-mcuboot, and then install a secondary image after that. 

After switching to the reloader-mcuboot image, and adding "PineDFU" to the accepted device aliases (`bluetooth.py line 100`), and trying to initiate a DFU of `micropython.zip`, the watch activates the bluetooth icon, siglo enters the firmware update screen, but never progresses past 0.  When siglo is run via CLI, the last line in console is "`[INFO ] Disabling GNOME idle timeout`", until the watch restarts

wasp-os version: `0.4.1`
siglo commit: `7eddd3c`

**Comment by alexr4535** [comment]
I wrote siglo for Infinitime, so there is currently no support wasp-os. if someone would like to do a PR to add support, I'd be happy to review and pull it in.
