### ISSUE TITLE
daemon mode documentation for mobile devices, e.g PinePhone

### ISSUE THREAD

**Issue by Utopiah** [alexr4535/siglo#75]
I'm trying to configure the PineTime with the PinePhone. As the phone has limited resources, both battery life and screen real estate, I'm trying to optimize that. I didn't find a command line interface but I noticed a daemon mode https://github.com/alexr4535/siglo/blob/main/src/siglo.in#L20

Could this be used for CLI pairing then synchronizing and if so how?

**Comment by alexr4535** [comment]
daemon mode works behind the scenes with systemd. It's not meant for end users. if you want to sync your watch via a script from command line you can use what i have here: https://github.com/alexr4535/Py-neTime
