### ISSUE TITLE
Siglo monitor "is not allowed to send messages"

### ISSUE THREAD

**Issue by jjs10** [alexr4535/siglo#82]
I was testing SMS notifications from my PinePhone running Mobian to my Infinitime watch and did not receive notification. I believe this is the corresponding error message from journalctl:

> 
> Sep 02 15:08:55 mobian systemd[665]: siglo.service: Failed with result 'exit-code'.
> Sep 02 15:08:55 mobian systemd[665]: siglo.service: Main process exited, code=exited, status=1/FAILURE
> Sep 02 15:08:55 mobian dbus-daemon[697]: [session uid=1000 pid=697] Monitoring connection :1.123 (uid=1000 pid=2409 comm="/usr/bin/python3 /usr/local/bin/siglo --start ") is not allowed to send messages; closing it. Please fix the monitor to not do that. (message type="error" interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" destination=":1.79")
> Sep 02 15:08:55 mobian siglo[2409]: {'category': 'SMS', 'sender': dbus.String('New message from Test Account'), 'message': dbus.String('Test SMS Message')}
> Sep 02 15:07:44 mobian dbus-daemon[697]: [session uid=1000 pid=697] Connection :1.123 (uid=1000 pid=2409 comm="/usr/bin/python3 /usr/local/bin/siglo --start ") became a monitor.
> Sep 02 15:07:44 mobian siglo[2409]: [f1:25:1c:7d:a1:48] Connection failed: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
> 

Is there a security setting that is needed to allow siglo to send messages?

**Comment by Yasumoto** [comment]
I think you're running into #80 :

https://github.com/alexr4535/siglo/issues/80#issuecomment-911691204

**Comment by jjs10** [comment]
> I think you're running into #80 :
> 
> [#80 (comment)](https://github.com/alexr4535/siglo/issues/80#issuecomment-911691204)

Possibly, I built from source instead of through flatpack and #80 sounded like it was specific to flatpack.

**Comment by jwillikers** [comment]
Does running `siglo --start` directly from the command-line produce the same errors? I bet the Systemd service unit needs modified to work better with DBus.

**Comment by jjs10** [comment]
> @jjs10 Does running `siglo --start` directly from the command-line produce the same errors? I bet the Systemd service unit needs modified to work better with DBus.

I just tried it using the `siglo --start` and not the systemd service and I get the same error message from journalctl and the siglo process dies when I received an SMS.

**Comment by jjs10** [comment]
This issue went away for me after I upgraded the watch to InfiniTime 1.6. I'm guessing it was related to the improvements to BLE they made on the watch itself.
