### ISSUE TITLE
No module named "requests"

### ISSUE THREAD

**Issue by InFerYes** [alexr4535/siglo#92]
I have installed Siglo on my PinePhone, but when I try to run it I get

```
[alarm@stripe siglo]$ siglo
Traceback (most recent call last):
  File "/usr/bin/siglo", line 46, in <module>
    main()
  File "/usr/bin/siglo", line 42, in main
    from siglo import main
  File "/usr/share/siglo/siglo/main.py", line 7, in <module>
    from .window import SigloWindow
  File "/usr/share/siglo/siglo/window.py", line 16, in <module>
    from .quick_deploy import *
  File "/usr/share/siglo/siglo/quick_deploy.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

```

I'm running Siglo on Phosh on Arch Linux ARM.

**Comment by alexr4535** [comment]
cannot reproduce. did you install from source or did you use the AUR or install from danct nix repo with pacman?

**Comment by InFerYes** [comment]
It has been installed via the AUR.

```
[alarm@stripe siglo]$ ls
pkg  PKGBUILD  siglo-0.9.4-1-any.pkg.tar.xz  siglo-0.9.4.tar.gz  src
```

**Comment by InFerYes** [comment]
I have installed Siglo via the repositories on the PinePhone now, and this hasn't come up anymore. Siglo launches now.

The repository version is 0.9.5-1, which is newer than the AUR version I had.
